/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLByteArray extends IDLArray {

    public static final IDLByteArray NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLByteArray native_new() {
        return new IDLByteArray((byte) 1, (char) 1);
    }

    protected IDLByteArray(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    protected IDLByteArray() {
        super((byte) 1, (char) 1);
    }

    public IDLByteArray(int size) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int(size);
        internal_reset(addr, true);
    }

    public void copy(byte[] array) {
        int length = array.length;
        resize(length);
        for (int i = 0; i < length; i++) {
            byte value = array[i];
            setValue(i, value);
        }
    }

    public static void arraycopy(byte[] src, int srcPos, IDLByteArray dest, int destPos, int length) {
        int srcP = srcPos;
        int destP = destPos;
        int count = 0;
        while (count < length) {
            byte srcByte = src[srcP];
            srcP++;
            dest.setValue(destP, srcByte);
            destP++;
            count++;
        }
    }

    public static void arraycopy(IDLByteArray src, int srcPos, byte[] dest, int destPos, int length) {
        int srcP = srcPos;
        int destP = destPos;
        int count = 0;
        while (count < length) {
            byte srcByte = src.getValue(srcP);
            srcP++;
            dest[destP] = srcByte;
            destP++;
            count++;
        }
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLByteArray((int)size);
    */
    public static native long internal_native_create_int(int size);

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public byte getValue(int index) {
        return internal_native_getValue(native_address, index);
    }

    /*
      [-JNI;-NATIVE]
      IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
      return nativeObject->getValue((int)index);
    */
    public static native byte internal_native_getValue(long this_addr, int index);

    public void setValue(int index, byte value) {
        internal_native_setValue(native_address, index, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
      nativeObject->setValue((int)index, value);
    */
    public static native void internal_native_setValue(long this_addr, int index, byte value);

    public void copy(IDLByteArray src, int srcOffset, int destOffset, int length) {
        internal_native_copy(native_address, src.native_address, srcOffset, destOffset, length);
    }

    /*
      [-JNI;-NATIVE]
      IDLByteArray* nativeObject = (IDLByteArray*)this_addr;
      nativeObject->copy(*((IDLByteArray* )src_addr), (int)srcOffset, (int)destOffset, (int)length);
    */
    public static native void internal_native_copy(long this_addr, long src_addr, int srcOffset, int destOffset, int length);
}
