/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLBool extends IDLBoolArray {

    public static final IDLBool NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLBool native_new() {
        return new IDLBool((byte) 1, (char) 1);
    }

    protected IDLBool(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLBool() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLBool();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLBool* nativeObject = (IDLBool*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public boolean getValue() {
        return internal_native_getValue(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLBool* nativeObject = (IDLBool*)this_addr;
      return nativeObject->getValue();
    */
    public static native boolean internal_native_getValue(long this_addr);

    public void set(boolean value) {
        internal_native_set(native_address, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLBool* nativeObject = (IDLBool*)this_addr;
      nativeObject->set(value);
    */
    public static native void internal_native_set(long this_addr, boolean value);
}
