/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLByte extends IDLByteArray {

    public static final IDLByte NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLByte native_new() {
        return new IDLByte((byte) 1, (char) 1);
    }

    protected IDLByte(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLByte() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLByte();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLByte* nativeObject = (IDLByte*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public byte getValue() {
        return internal_native_getValue(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLByte* nativeObject = (IDLByte*)this_addr;
      return nativeObject->getValue();
    */
    public static native byte internal_native_getValue(long this_addr);

    public void set(byte value) {
        internal_native_set(native_address, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLByte* nativeObject = (IDLByte*)this_addr;
      nativeObject->set(value);
    */
    public static native void internal_native_set(long this_addr, byte value);
}
