/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLBoolArray extends IDLArray {

    public static final IDLBoolArray NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLBoolArray native_new() {
        return new IDLBoolArray((byte) 1, (char) 1);
    }

    protected IDLBoolArray(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    protected IDLBoolArray() {
        super((byte) 1, (char) 1);
    }

    public IDLBoolArray(int size) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int(size);
        internal_reset(addr, true);
    }

    public void copy(boolean[] array) {
        int length = array.length;
        resize(length);
        for (int i = 0; i < length; i++) {
            boolean value = array[i];
            setValue(i, value);
        }
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLBoolArray((int)size);
    */
    public static native long internal_native_create_int(int size);

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLBoolArray* nativeObject = (IDLBoolArray*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public boolean getValue(int index) {
        return internal_native_getValue(native_address, index);
    }

    /*
      [-JNI;-NATIVE]
      IDLBoolArray* nativeObject = (IDLBoolArray*)this_addr;
      return nativeObject->getValue((int)index);
    */
    public static native boolean internal_native_getValue(long this_addr, int index);

    public void setValue(int index, boolean value) {
        internal_native_setValue(native_address, index, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLBoolArray* nativeObject = (IDLBoolArray*)this_addr;
      nativeObject->setValue((int)index, value);
    */
    public static native void internal_native_setValue(long this_addr, int index, boolean value);

    public void copy(IDLBoolArray src, int srcOffset, int destOffset, int length) {
        internal_native_copy(native_address, src.native_address, srcOffset, destOffset, length);
    }

    /*
      [-JNI;-NATIVE]
      IDLBoolArray* nativeObject = (IDLBoolArray*)this_addr;
      nativeObject->copy(*((IDLBoolArray* )src_addr), (int)srcOffset, (int)destOffset, (int)length);
    */
    public static native void internal_native_copy(long this_addr, long src_addr, int srcOffset, int destOffset, int length);
}
