/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLDouble4 extends IDLDoubleArray {

    public static final IDLDouble4 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLDouble4 native_new() {
        return new IDLDouble4((byte) 1, (char) 1);
    }

    protected IDLDouble4(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLDouble4() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLDouble4();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble4* nativeObject = (IDLDouble4*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(double x, double y, double z, double w) {
        internal_native_set(native_address, x, y, z, w);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble4* nativeObject = (IDLDouble4*)this_addr;
      nativeObject->set((double)x, (double)y, (double)z, (double)w);
    */
    public static native void internal_native_set(long this_addr, double x, double y, double z, double w);

    public double getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble4* nativeObject = (IDLDouble4*)this_addr;
      return nativeObject->getX();
    */
    public static native double internal_native_getX(long this_addr);

    public double getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble4* nativeObject = (IDLDouble4*)this_addr;
      return nativeObject->getY();
    */
    public static native double internal_native_getY(long this_addr);

    public double getZ() {
        return internal_native_getZ(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble4* nativeObject = (IDLDouble4*)this_addr;
      return nativeObject->getZ();
    */
    public static native double internal_native_getZ(long this_addr);

    public double getW() {
        return internal_native_getW(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble4* nativeObject = (IDLDouble4*)this_addr;
      return nativeObject->getW();
    */
    public static native double internal_native_getW(long this_addr);
}
