/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLDouble extends IDLDoubleArray {

    public static final IDLDouble NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLDouble native_new() {
        return new IDLDouble((byte) 1, (char) 1);
    }

    protected IDLDouble(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLDouble() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLDouble();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble* nativeObject = (IDLDouble*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public double getValue() {
        return internal_native_getValue(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble* nativeObject = (IDLDouble*)this_addr;
      return nativeObject->getValue();
    */
    public static native double internal_native_getValue(long this_addr);

    public void set(double value) {
        internal_native_set(native_address, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble* nativeObject = (IDLDouble*)this_addr;
      nativeObject->set((double)value);
    */
    public static native void internal_native_set(long this_addr, double value);
}
