/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLDouble3 extends IDLDoubleArray {

    public static final IDLDouble3 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLDouble3 native_new() {
        return new IDLDouble3((byte) 1, (char) 1);
    }

    protected IDLDouble3(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLDouble3() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLDouble3();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble3* nativeObject = (IDLDouble3*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(double x, double y, double z) {
        internal_native_set(native_address, x, y, z);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble3* nativeObject = (IDLDouble3*)this_addr;
      nativeObject->set((double)x, (double)y, (double)z);
    */
    public static native void internal_native_set(long this_addr, double x, double y, double z);

    public double getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble3* nativeObject = (IDLDouble3*)this_addr;
      return nativeObject->getX();
    */
    public static native double internal_native_getX(long this_addr);

    public double getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble3* nativeObject = (IDLDouble3*)this_addr;
      return nativeObject->getY();
    */
    public static native double internal_native_getY(long this_addr);

    public double getZ() {
        return internal_native_getZ(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLDouble3* nativeObject = (IDLDouble3*)this_addr;
      return nativeObject->getZ();
    */
    public static native double internal_native_getZ(long this_addr);
}
