/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLFloat2 extends IDLFloatArray {

    public static final IDLFloat2 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLFloat2 native_new() {
        return new IDLFloat2((byte) 1, (char) 1);
    }

    protected IDLFloat2(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLFloat2() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLFloat2();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat2* nativeObject = (IDLFloat2*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(float x, float y) {
        internal_native_set(native_address, x, y);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat2* nativeObject = (IDLFloat2*)this_addr;
      nativeObject->set((float)x, (float)y);
    */
    public static native void internal_native_set(long this_addr, float x, float y);

    public float getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat2* nativeObject = (IDLFloat2*)this_addr;
      return nativeObject->getX();
    */
    public static native float internal_native_getX(long this_addr);

    public float getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat2* nativeObject = (IDLFloat2*)this_addr;
      return nativeObject->getY();
    */
    public static native float internal_native_getY(long this_addr);
}
