/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLFloat extends IDLFloatArray {

    public static final IDLFloat NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLFloat native_new() {
        return new IDLFloat((byte) 1, (char) 1);
    }

    protected IDLFloat(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLFloat() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLFloat();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat* nativeObject = (IDLFloat*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public float getValue() {
        return internal_native_getValue(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat* nativeObject = (IDLFloat*)this_addr;
      return nativeObject->getValue();
    */
    public static native float internal_native_getValue(long this_addr);

    public void set(float value) {
        internal_native_set(native_address, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat* nativeObject = (IDLFloat*)this_addr;
      nativeObject->set((float)value);
    */
    public static native void internal_native_set(long this_addr, float value);
}
