/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLFloat4 extends IDLFloatArray {

    public static final IDLFloat4 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLFloat4 native_new() {
        return new IDLFloat4((byte) 1, (char) 1);
    }

    protected IDLFloat4(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLFloat4() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLFloat4();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat4* nativeObject = (IDLFloat4*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(float x, float y, float z, float w) {
        internal_native_set(native_address, x, y, z, w);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat4* nativeObject = (IDLFloat4*)this_addr;
      nativeObject->set((float)x, (float)y, (float)z, (float)w);
    */
    public static native void internal_native_set(long this_addr, float x, float y, float z, float w);

    public float getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat4* nativeObject = (IDLFloat4*)this_addr;
      return nativeObject->getX();
    */
    public static native float internal_native_getX(long this_addr);

    public float getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat4* nativeObject = (IDLFloat4*)this_addr;
      return nativeObject->getY();
    */
    public static native float internal_native_getY(long this_addr);

    public float getZ() {
        return internal_native_getZ(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat4* nativeObject = (IDLFloat4*)this_addr;
      return nativeObject->getZ();
    */
    public static native float internal_native_getZ(long this_addr);

    public float getW() {
        return internal_native_getW(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLFloat4* nativeObject = (IDLFloat4*)this_addr;
      return nativeObject->getW();
    */
    public static native float internal_native_getW(long this_addr);
}
