/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLInt2 extends IDLIntArray {

    public static final IDLInt2 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLInt2 native_new() {
        return new IDLInt2((byte) 1, (char) 1);
    }

    protected IDLInt2(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLInt2() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLInt2();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt2* nativeObject = (IDLInt2*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(int x, int y) {
        internal_native_set(native_address, x, y);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt2* nativeObject = (IDLInt2*)this_addr;
      nativeObject->set((int)x, (int)y);
    */
    public static native void internal_native_set(long this_addr, int x, int y);

    public int getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt2* nativeObject = (IDLInt2*)this_addr;
      return nativeObject->getX();
    */
    public static native int internal_native_getX(long this_addr);

    public int getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt2* nativeObject = (IDLInt2*)this_addr;
      return nativeObject->getY();
    */
    public static native int internal_native_getY(long this_addr);
}
