/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLIntArray extends IDLArray {

    public static final IDLIntArray NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLIntArray native_new() {
        return new IDLIntArray((byte) 1, (char) 1);
    }

    protected IDLIntArray() {
        super((byte) 1, (char) 1);
    }

    protected IDLIntArray(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLIntArray(int size) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int(size);
        internal_reset(addr, true);
    }

    public void copy(int[] array) {
        int length = array.length;
        resize(length);
        for (int i = 0; i < length; i++) {
            int value = array[i];
            setValue(i, value);
        }
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLIntArray((int)size);
    */
    public static native long internal_native_create_int(int size);

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLIntArray* nativeObject = (IDLIntArray*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public int getValue(int index) {
        return internal_native_getValue(native_address, index);
    }

    /*
      [-JNI;-NATIVE]
      IDLIntArray* nativeObject = (IDLIntArray*)this_addr;
      return nativeObject->getValue((int)index);
    */
    public static native int internal_native_getValue(long this_addr, int index);

    public void setValue(int index, int value) {
        internal_native_setValue(native_address, index, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLIntArray* nativeObject = (IDLIntArray*)this_addr;
      nativeObject->setValue((int)index, (int)value);
    */
    public static native void internal_native_setValue(long this_addr, int index, int value);

    public void copy(IDLIntArray src, int srcOffset, int destOffset, int length) {
        internal_native_copy(native_address, src.native_address, srcOffset, destOffset, length);
    }

    /*
      [-JNI;-NATIVE]
      IDLIntArray* nativeObject = (IDLIntArray*)this_addr;
      nativeObject->copy(*((IDLIntArray* )src_addr), (int)srcOffset, (int)destOffset, (int)length);
    */
    public static native void internal_native_copy(long this_addr, long src_addr, int srcOffset, int destOffset, int length);
}
