/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLInt4 extends IDLIntArray {

    public static final IDLInt4 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLInt4 native_new() {
        return new IDLInt4((byte) 1, (char) 1);
    }

    protected IDLInt4(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLInt4() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLInt4();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt4* nativeObject = (IDLInt4*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(int x, int y, int z, int w) {
        internal_native_set(native_address, x, y, z, w);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt4* nativeObject = (IDLInt4*)this_addr;
      nativeObject->set((int)x, (int)y, (int)z, (int)w);
    */
    public static native void internal_native_set(long this_addr, int x, int y, int z, int w);

    public int getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt4* nativeObject = (IDLInt4*)this_addr;
      return nativeObject->getX();
    */
    public static native int internal_native_getX(long this_addr);

    public int getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt4* nativeObject = (IDLInt4*)this_addr;
      return nativeObject->getY();
    */
    public static native int internal_native_getY(long this_addr);

    public int getZ() {
        return internal_native_getZ(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt4* nativeObject = (IDLInt4*)this_addr;
      return nativeObject->getZ();
    */
    public static native int internal_native_getZ(long this_addr);

    public int getW() {
        return internal_native_getW(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt4* nativeObject = (IDLInt4*)this_addr;
      return nativeObject->getW();
    */
    public static native int internal_native_getW(long this_addr);
}
