/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLInt extends IDLIntArray {

    public static final IDLInt NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLInt native_new() {
        return new IDLInt((byte) 1, (char) 1);
    }

    protected IDLInt(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLInt() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLInt();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt* nativeObject = (IDLInt*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public int getValue() {
        return internal_native_getValue(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt* nativeObject = (IDLInt*)this_addr;
      return nativeObject->getValue();
    */
    public static native int internal_native_getValue(long this_addr);

    public void set(int value) {
        internal_native_set(native_address, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLInt* nativeObject = (IDLInt*)this_addr;
      nativeObject->set((int)value);
    */
    public static native void internal_native_set(long this_addr, int value);
}
