/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLLong extends IDLLongArray {

    public static final IDLLong NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLLong native_new() {
        return new IDLLong((byte) 1, (char) 1);
    }

    protected IDLLong(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLLong() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLLong();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong* nativeObject = (IDLLong*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public long getValue() {
        return internal_native_getValue(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong* nativeObject = (IDLLong*)this_addr;
      return nativeObject->getValue();
    */
    public static native long internal_native_getValue(long this_addr);

    public void set(long value) {
        internal_native_set(native_address, value);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong* nativeObject = (IDLLong*)this_addr;
      nativeObject->set(value);
    */
    public static native void internal_native_set(long this_addr, long value);
}
