/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLLong2 extends IDLLongArray {

    public static final IDLLong2 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLLong2 native_new() {
        return new IDLLong2((byte) 1, (char) 1);
    }

    protected IDLLong2(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLLong2() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLLong2();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong2* nativeObject = (IDLLong2*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(long x, long y) {
        internal_native_set(native_address, x, y);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong2* nativeObject = (IDLLong2*)this_addr;
      nativeObject->set(x, y);
    */
    public static native void internal_native_set(long this_addr, long x, long y);

    public long getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong2* nativeObject = (IDLLong2*)this_addr;
      return nativeObject->getX();
    */
    public static native long internal_native_getX(long this_addr);

    public long getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong2* nativeObject = (IDLLong2*)this_addr;
      return nativeObject->getY();
    */
    public static native long internal_native_getY(long this_addr);
}
