/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

public class IDLLong3 extends IDLLongArray {

    public static final IDLLong3 NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLLong3 native_new() {
        return new IDLLong3((byte) 1, (char) 1);
    }

    protected IDLLong3(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    public IDLLong3() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLLong3();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong3* nativeObject = (IDLLong3*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void set(long x, long y, long z) {
        internal_native_set(native_address, x, y, z);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong3* nativeObject = (IDLLong3*)this_addr;
      nativeObject->set(x, y, z);
    */
    public static native void internal_native_set(long this_addr, long x, long y, long z);

    public long getX() {
        return internal_native_getX(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong3* nativeObject = (IDLLong3*)this_addr;
      return nativeObject->getX();
    */
    public static native long internal_native_getX(long this_addr);

    public long getY() {
        return internal_native_getY(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong3* nativeObject = (IDLLong3*)this_addr;
      return nativeObject->getY();
    */
    public static native long internal_native_getY(long this_addr);

    public long getZ() {
        return internal_native_getZ(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLLong3* nativeObject = (IDLLong3*)this_addr;
      return nativeObject->getZ();
    */
    public static native long internal_native_getZ(long this_addr);
}
