/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

import com.github.xpenatan.jParser.idl.IDLBase;

public class IDLString extends IDLBase {

    public static final IDLString NULL = native_new();

    /**
     * @return An empty instance without a native address
     */
    public static IDLString native_new() {
        return new IDLString((byte) 1, (char) 1);
    }

    protected IDLString(byte b, char c) {
    }

    public IDLString() {
        long addr = internal_native_create();
        internal_reset(addr, true);
    }

    public String c_str() {
        String text = internal_native_c_str(native_address);
        return text;
    }

    /*
      [-JNI;-NATIVE]
              IDLString* nativeObject = (IDLString*)this_addr;
              const char* str = nativeObject->c_str();
              jstring jstrBuf = env->NewStringUTF(str);
              return jstrBuf;
    */
    private static native String internal_native_c_str(long this_addr);

    public String data() {
        String text = internal_native_data(native_address);
        return text;
    }

    /*
      [-JNI;-NATIVE]
              IDLString* nativeObject = (IDLString*)this_addr;
              const char* str = nativeObject->data();
              jstring jstrBuf = env->NewStringUTF(str);
              return jstrBuf;
    */
    private static native String internal_native_data(long this_addr);

    /*
      [-JNI;-NATIVE]
      return (jlong)new IDLString();
    */
    public static native long internal_native_create();

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLString* nativeObject = (IDLString*)this_addr;
      delete nativeObject;
    */
    public static native void internal_native_deleteNative(long this_addr);

    public void clear() {
        internal_native_clear(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLString* nativeObject = (IDLString*)this_addr;
      nativeObject->clear();
    */
    public static native void internal_native_clear(long this_addr);

    public void append(String text) {
        internal_native_append(native_address, text);
    }

    /*
      [-JNI;-NATIVE]
      IDLString* nativeObject = (IDLString*)this_addr;
      nativeObject->append(text);
    */
    public static native void internal_native_append(long this_addr, String text);

    public void append(String text, int size) {
        internal_native_append(native_address, text, size);
    }

    /*
      [-JNI;-NATIVE]
      IDLString* nativeObject = (IDLString*)this_addr;
      nativeObject->append(text, (int)size);
    */
    public static native void internal_native_append(long this_addr, String text, int size);

    public int size() {
        return internal_native_size(native_address);
    }

    /*
      [-JNI;-NATIVE]
      IDLString* nativeObject = (IDLString*)this_addr;
      return nativeObject->size();
    */
    public static native int internal_native_size(long this_addr);

    public byte at(int index) {
        return internal_native_at(native_address, index);
    }

    /*
      [-JNI;-NATIVE]
      IDLString* nativeObject = (IDLString*)this_addr;
      return nativeObject->at((int)index);
    */
    public static native byte internal_native_at(long this_addr, int index);
}
