/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua.idl.helper;

import com.github.xpenatan.jParser.idl.IDLBase;
import java.nio.ByteBuffer;

public class IDLUtils {

    /*
      [-JNI;-NATIVE]
              #include <cstring>
    */
    public static String getJSString(long addr) {
        return null;
    }

    public static void copyToByteBuffer(IDLBase source, ByteBuffer destination, long offset, long sizeInBytes) {
        internal_native_copyToByteBuffer(source.native_void_address, destination, offset, sizeInBytes);
    }

    /*
      [-JNI;-NATIVE]
              void* data = (void*)data_addr;
              char* bufferAddress = (char*)env->GetDirectBufferAddress(destination);
              memcpy(bufferAddress + offset, data, sizeInBytes);
    */
    public static native void internal_native_copyToByteBuffer(long data_addr, ByteBuffer destination, long offset, long sizeInBytes);
}
