/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package lua;

import com.github.xpenatan.jParser.loader.JParserLibraryLoader;
import com.github.xpenatan.jParser.loader.JParserLibraryLoaderListener;

/**
 * @author xpenatan
 */
public class LuaLoader {

    /*
      [-JNI;-NATIVE]
              #include "LuaCustom.h"
    */
    public static void init(JParserLibraryLoaderListener listener) {
        JParserLibraryLoader.load("lua", listener);
    }
}
